//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPDHI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSSPDHIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSSPDHIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPDHI.Resources.CSSPDHIRes", typeof(CSSPDHIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary conditions file name.
        /// </summary>
        public static string BoundaryConditionsFileName {
            get {
                return ResourceManager.GetString("BoundaryConditionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create [{0}].
        /// </summary>
        public static string CouldNotCreate_ {
            get {
                return ResourceManager.GetString("CouldNotCreate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find [{0}] with [{1}] equal [{2}].
        /// </summary>
        public static string CouldNotFind_With_Equal_ {
            get {
                return ResourceManager.GetString("CouldNotFind_With_Equal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file [{0}].
        /// </summary>
        public static string CouldNotFindFile_ {
            get {
                return ResourceManager.GetString("CouldNotFindFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find section for path [{0}].
        /// </summary>
        public static string CouldNotFindSectionForPath_ {
            get {
                return ResourceManager.GetString("CouldNotFindSectionForPath_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open [{0}]. Error: [{1}].
        /// </summary>
        public static string CouldNotOpen_Error_ {
            get {
                return ResourceManager.GetString("CouldNotOpen_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read value with path [{0}] and keyword [{1}]. Error [{2}].
        /// </summary>
        public static string CouldNotReadValueWithPath_AndKeyword_Error_ {
            get {
                return ResourceManager.GetString("CouldNotReadValueWithPath_AndKeyword_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set start time with path [{0}] and keyword [{1}]. Error [{2}].
        /// </summary>
        public static string CouldNotSetStartTimeWithPath_Keyword_Error_ {
            get {
                return ResourceManager.GetString("CouldNotSetStartTimeWithPath_Keyword_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type is other than [{0}]. It&apos;s [{1}]..
        /// </summary>
        public static string ElementTypeIsOtherThan_Its_ {
            get {
                return ResourceManager.GetString("ElementTypeIsOtherThan_Its_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File [{0}] does not exist.
        /// </summary>
        public static string File_DoesNotExist {
            get {
                return ResourceManager.GetString("File_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains 2 parameters but they are not of type [eumItem.eumIuVelocity and eumItem.eumIvVelocity]. It is [{0}] and [{1}]..
        /// </summary>
        public static string FileContains2ParamButItsNotOfUVAndVVItIs_And_ {
            get {
                return ResourceManager.GetString("FileContains2ParamButItsNotOfUVAndVVItIs_And_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains one parameter but its not of type [eumItem.eumIWaterLevel] or [eumItem.eumIWaterDepth]. It is [{0}]..
        /// </summary>
        public static string FileContainsOneParamButItsNotOfTypeWLOrWDItIs_ {
            get {
                return ResourceManager.GetString("FileContainsOneParamButItsNotOfTypeWLOrWDItIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword [{0}] does not exist for section path [{1}]. Error: [{2}].
        /// </summary>
        public static string Keyword_DoesNotExistForSectionPath_Error_ {
            get {
                return ResourceManager.GetString("Keyword_DoesNotExistForSectionPath_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of web tide nodes is 0.
        /// </summary>
        public static string NumberOfWebTideNodesIsZero {
            get {
                return ResourceManager.GetString("NumberOfWebTideNodesIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter [{0}] does not exist for section path [{1}] and keyword [{2}]. Error: [{3}].
        /// </summary>
        public static string ParameterIndex_DoesNotExistForSectionPath_AndKeyword_Error_ {
            get {
                return ResourceManager.GetString("ParameterIndex_DoesNotExistForSectionPath_AndKeyword_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potentially wrong file type. Looking for {0}. Error: [{1}].
        /// </summary>
        public static string PotentiallyWrongFileTypeLookingFor_Error_ {
            get {
                return ResourceManager.GetString("PotentiallyWrongFileTypeLookingFor_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server file name.
        /// </summary>
        public static string ServerFileName {
            get {
                return ResourceManager.GetString("ServerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file type. Looking for {0}.
        /// </summary>
        public static string WrongFileTypeLookingFor_ {
            get {
                return ResourceManager.GetString("WrongFileTypeLookingFor_", resourceCulture);
            }
        }
    }
}
